-- =====================================================================
-- 备件档案更名为「酒企配套厂」场景
-- 保持 id/code 不变，避免破坏采购/库存/领用/设备配套外键
-- 用法：mysql -u admin -p spare_db < sql/rename_spare_parts_liquor_plant.sql
-- =====================================================================
SET NAMES utf8mb4;
USE spare_db;

-- 分类名称更贴近酒企备件管理
UPDATE spare_part_category SET name = '包材与瓶盖耗材' WHERE id = 1;
UPDATE spare_part_category SET name = '酿造电气控制'   WHERE id = 2;
UPDATE spare_part_category SET name = '灌装线传动件'   WHERE id = 3;
UPDATE spare_part_category SET name = '气动与气源'     WHERE id = 4;
UPDATE spare_part_category SET name = '酒液管路与泵阀' WHERE id = 5;
UPDATE spare_part_category SET name = '灌装关键件/量具' WHERE id = 6;
UPDATE spare_part_category SET name = '酒线传感检测'   WHERE id = 7;
UPDATE spare_part_category SET name = '食品级紧固件'   WHERE id = 8;
UPDATE spare_part_category SET name = '食品级密封件'   WHERE id = 9;
UPDATE spare_part_category SET name = '灌装/码垛轴承' WHERE id = 10;

-- id 保持 1~50，仅更新名称/型号/供应商等展示字段
UPDATE spare_part SET
  name = CASE id
    WHEN 1  THEN '灌装机转台支撑轴承'
    WHEN 2  THEN '灌装线主驱动变频器'
    WHEN 3  THEN '瓶位光电检测传感器'
    WHEN 4  THEN '拨瓶星轮气缸'
    WHEN 5  THEN '瓶盖到位接近开关'
    WHEN 6  THEN '配电柜微型断路器'
    WHEN 7  THEN '码垛伺服电机'
    WHEN 8  THEN '食品级输酒硅胶软管'
    WHEN 9  THEN '贴标机横移导轨滑块'
    WHEN 10 THEN '灌装电机交流接触器'
    WHEN 11 THEN '包装线PLC数字量模块'
    WHEN 12 THEN '码垛机回转支承轴承'
    WHEN 13 THEN '灌装阀食品级密封圈'
    WHEN 14 THEN '食品级不锈钢内六角螺钉'
    WHEN 15 THEN '旋盖机气动电磁阀'
    WHEN 16 THEN '灌装阀硬质合金阀芯'
    WHEN 17 THEN 'CIP不锈钢离心泵'
    WHEN 18 THEN '酒管路不锈钢止回阀'
    WHEN 19 THEN '产线工业以太网交换机'
    WHEN 20 THEN '酒罐铂电阻温度探头'
    WHEN 21 THEN '控制柜开关电源'
    WHEN 22 THEN '甑桶盖推力轴承'
    WHEN 23 THEN '空压站气源三联件'
    WHEN 24 THEN '气缸磁性位置开关'
    WHEN 25 THEN '中间继电器'
    WHEN 26 THEN '贴标机同步传动带'
    WHEN 27 THEN '旋盖主轴弹性联轴器'
    WHEN 28 THEN '装箱机蜗轮减速机'
    WHEN 29 THEN '操作盒启动按钮'
    WHEN 30 THEN '急停蘑菇头按钮'
    WHEN 31 THEN '状态指示灯'
    WHEN 32 THEN '安全门行程开关'
    WHEN 33 THEN '瓶身外观检测光栅'
    WHEN 34 THEN '无油空压机精密滤芯'
    WHEN 35 THEN '升降挡瓶油压缓冲器'
    WHEN 36 THEN '法兰食品级紫铜垫圈'
    WHEN 37 THEN '输酒泵机械密封油封'
    WHEN 38 THEN '食品级弹簧垫圈'
    WHEN 39 THEN '不锈钢自攻螺丝'
    WHEN 40 THEN '设备底座膨胀螺栓'
    WHEN 41 THEN '旋盖机硅胶旋盖头'
    WHEN 42 THEN '食品级润滑脂'
    WHEN 43 THEN 'CIP清洗专用碱液'
    WHEN 44 THEN '电缆扎带'
    WHEN 45 THEN '电气绝缘胶布'
    WHEN 46 THEN '灌装阀拆装扳手组'
    WHEN 47 THEN '管路活扳手'
    WHEN 48 THEN '瓶口尺寸数显卡尺'
    WHEN 49 THEN '阀芯外径千分尺'
    WHEN 50 THEN '电气检修万用表'
  END,
  model = CASE id
    WHEN 1  THEN 'XGF-24 转台用 6205-2RS 食品级'
    WHEN 2  THEN 'ACS580-01-09A5 灌装线专用'
    WHEN 3  THEN 'E3Z-D62 瓶位检测'
    WHEN 4  THEN 'CDQ2B32-50D 拨瓶'
    WHEN 5  THEN 'E2E-X5ME1 瓶盖检测'
    WHEN 6  THEN 'iC65N C16A 2P'
    WHEN 7  THEN '1FL6042 码垛轴'
    WHEN 8  THEN 'Φ25×Φ33 食品级硅胶'
    WHEN 9  THEN 'HSR15R 贴标横移'
    WHEN 10 THEN 'CJX2-1810 18A'
    WHEN 11 THEN 'S7-1500 DI 32点'
    WHEN 12 THEN 'NU206 码垛回转'
    WHEN 13 THEN 'Φ25×3.5 硅胶 食品级'
    WHEN 14 THEN 'M8×30 304'
    WHEN 15 THEN 'SY5120 旋盖气路'
    WHEN 16 THEN 'XGF-24 灌装阀芯'
    WHEN 17 THEN 'CHL4-30 CIP/输酒'
    WHEN 18 THEN 'H12W-16P DN25'
    WHEN 19 THEN 'SCALANCE XB005'
    WHEN 20 THEN 'Pt100 A级 酒罐'
    WHEN 21 THEN 'NDR-120-24'
    WHEN 22 THEN '51105 甑桶盖'
    WHEN 23 THEN 'AC30-03G'
    WHEN 24 THEN 'D-A93'
    WHEN 25 THEN 'JZX-22F 24VDC'
    WHEN 26 THEN '5M-450 贴标传动'
    WHEN 27 THEN 'ML-42 旋盖轴'
    WHEN 28 THEN 'SA37 装箱减速'
    WHEN 29 THEN 'XB4BA31'
    WHEN 30 THEN 'XB4BS8442'
    WHEN 31 THEN 'XB4BVB3'
    WHEN 32 THEN 'D4V-8108 安全门'
    WHEN 33 THEN 'GL-R32H 瓶检'
    WHEN 34 THEN '1613-7508-00 空压滤芯'
    WHEN 35 THEN 'RBC1007 挡瓶'
    WHEN 36 THEN 'Φ20×Φ14×2 食品级'
    WHEN 37 THEN 'TC25×42×10 输酒泵'
    WHEN 38 THEN 'M8 304'
    WHEN 39 THEN 'M5×16 304'
    WHEN 40 THEN 'M10×100'
    WHEN 41 THEN 'YXG-12 硅胶旋盖头'
    WHEN 42 THEN 'LGFP2 食品级'
    WHEN 43 THEN 'NaOH 2% 25kg'
    WHEN 44 THEN '4.8×300 白'
    WHEN 45 THEN '电工绝缘 0.15×18'
    WHEN 46 THEN '灌装阀专用组套'
    WHEN 47 THEN '12寸 管路检修'
    WHEN 48 THEN '0-150mm 瓶口检测'
    WHEN 49 THEN '0-25mm 阀芯'
    WHEN 50 THEN '数字式 电气检修'
  END,
  unit = CASE id
    WHEN 8 THEN '米'
    WHEN 14 THEN '盒'
    WHEN 16 THEN '套'
    WHEN 36 THEN '包'
    WHEN 38 THEN '盒'
    WHEN 39 THEN '盒'
    WHEN 40 THEN '包'
    WHEN 42 THEN '桶'
    WHEN 43 THEN '桶'
    WHEN 44 THEN '包'
    WHEN 45 THEN '卷'
    WHEN 46 THEN '套'
    WHEN 47 THEN '把'
    WHEN 48 THEN '把'
    WHEN 49 THEN '把'
    WHEN 50 THEN '台'
    WHEN 2 THEN '台'
    WHEN 7 THEN '台'
    WHEN 28 THEN '台'
    ELSE unit
  END,
  supplier = CASE id
    WHEN 1  THEN '新美星灌装配套'
    WHEN 2  THEN '新美星/达意隆电气配套'
    WHEN 3  THEN '包装线传感配套厂'
    WHEN 4  THEN '永创/新美星气动配套'
    WHEN 5  THEN '瓶盖输送配套厂'
    WHEN 6  THEN '酒企电气成套厂'
    WHEN 7  THEN '南京轻机码垛配套'
    WHEN 8  THEN '食品级软管配套厂'
    WHEN 9  THEN '兄弟贴标机配套'
    WHEN 10 THEN '包装线电气配套'
    WHEN 11 THEN '包装线自动化配套'
    WHEN 12 THEN '码垛线机械配套'
    WHEN 13 THEN '灌装阀密封件厂'
    WHEN 14 THEN '食品级紧固件厂'
    WHEN 15 THEN '永创旋盖机配套'
    WHEN 16 THEN '新美星灌装阀配件'
    WHEN 17 THEN '阿法拉伐CIP配套'
    WHEN 18 THEN '酒管路阀门厂'
    WHEN 19 THEN '产线网络配套'
    WHEN 20 THEN '酒罐仪表配套'
    WHEN 21 THEN '电气成套厂'
    WHEN 22 THEN '甑桶蒸馏配套'
    WHEN 23 THEN '空压站配套'
    WHEN 24 THEN '气动元件配套'
    WHEN 25 THEN '电气成套厂'
    WHEN 26 THEN '贴标机传动配套'
    WHEN 27 THEN '旋盖机传动配套'
    WHEN 28 THEN '装箱码垛配套'
    WHEN 29 THEN '操作盘配套'
    WHEN 30 THEN '安全元器件配套'
    WHEN 31 THEN '操作盘配套'
    WHEN 32 THEN '安全防护配套'
    WHEN 33 THEN '瓶检视觉配套'
    WHEN 34 THEN '空压机耗材配套'
    WHEN 35 THEN '灌装线气动配套'
    WHEN 36 THEN '食品级密封垫厂'
    WHEN 37 THEN '输酒泵密封配套'
    WHEN 38 THEN '食品级紧固件厂'
    WHEN 39 THEN '食品级紧固件厂'
    WHEN 40 THEN '设备安装配套'
    WHEN 41 THEN '永创旋盖耗材'
    WHEN 42 THEN '食品级润滑配套'
    WHEN 43 THEN 'CIP清洗药剂厂'
    WHEN 44 THEN '电气辅料'
    WHEN 45 THEN '电气辅料'
    WHEN 46 THEN '灌装维修工具'
    WHEN 47 THEN '机修工具'
    WHEN 48 THEN '质量检测量具'
    WHEN 49 THEN '质量检测量具'
    WHEN 50 THEN '电气检修仪表'
  END,
  remark = CASE
    WHEN id IN (16,41,13,8,17,18,43) THEN '酒企包装/酿造关键易损件'
    WHEN id IN (1,2,7,11,12,28,34) THEN '酒企主线设备关键备件'
    ELSE '酒企配套厂常用备件'
  END
WHERE id BETWEEN 1 AND 50;

-- 校验
SELECT id, code, name, model, supplier FROM spare_part ORDER BY id;
SELECT id, name FROM spare_part_category ORDER BY id;
